// Code generated by Prismic. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
	navigation_dropdown: defineAsyncComponent(() => import("./NavigationDropdown/index.vue")),
	navigation_link: defineAsyncComponent(() => import("./NavigationLink/index.vue"))
});